openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /organisations:
    get:
      summary: List Organisations
      operationId: list_organisations_organisations_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Organisation'
                type: array
                title: Response List Organisations Organisations Get
  /catalogue:
    get:
      summary: Search Catalogue
      operationId: search_catalogue_catalogue_get
      parameters:
        - name: query
          in: query
          required: false
          schema:
            type: string
            title: Query
        - name: topic
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
            default: []
            title: Topic
        - name: organisation
          in: query
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/organisationID'
            default: []
            title: Organisation
        - name: assetType
          in: query
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/assetType'
            default: []
            title: Assettype
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 100
            title: Limit
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
            title: Offset
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchAssetsResponse'
                title: Response Search Catalogue Catalogue Get
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /catalogue/{asset_id}:
    get:
      summary: Catalogue Entry Detail
      operationId: catalogue_entry_detail_catalogue__asset_id__get
      parameters:
        - name: asset_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            title: Asset Id
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataAsset'
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ContactPoint:
      properties:
        contactName:
          anyOf:
            - type: string
            - type: "null"
          title: Contactname
        email:
          type: string
          pattern: ([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+
          title: Email
          description: Valid email address
          examples:
            - user@domain.com
      type: object
      required:
        - email
      title: ContactPoint
    DataAsset:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        publisher:
          $ref: '#/components/schemas/Organisation'
        title:
          type: string
          title: Title
        description:
          type: string
          title: Description
        created:
          type: string
          format: date-time
          title: Created
        type:
          $ref: '#/components/schemas/assetType'
        modified:
          anyOf:
            - type: string
              format: date-time
            - type: "null"
          title: Modified
        alternativeTitle:
          anyOf:
            - items:
                type: string
              type: array
            - type: "null"
          title: Alternativetitle
          default: []
        issued:
          anyOf:
            - type: string
              format: date-time
            - type: "null"
          title: Issued
        accessRights:
          anyOf:
            - $ref: '#/components/schemas/rightsStatement'
            - type: "null"
        contactPoint:
          $ref: '#/components/schemas/ContactPoint'
        keyword:
          anyOf:
            - items:
                type: string
              type: array
            - type: "null"
          title: Keyword
          default: []
        relatedAssets:
          anyOf:
            - items:
                type: string
                minLength: 1
                format: uri
              type: array
            - type: "null"
          title: Relatedassets
          default: []
        summary:
          anyOf:
            - type: string
            - type: "null"
          title: Summary
        theme:
          anyOf:
            - items:
                type: string
                minLength: 1
                format: uri
              type: array
            - type: "null"
          title: Theme
          default: []
        licence:
          anyOf:
            - type: string
              minLength: 1
              format: uri
            - type: "null"
          title: Licence
          default: https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
        securityClassification:
          anyOf:
            - $ref: '#/components/schemas/securityClass'
            - type: "null"
          default: OFFICIAL
        version:
          anyOf:
            - type: string
            - type: "null"
          title: Version
          default: "1.0"
        creator:
          anyOf:
            - items:
                $ref: '#/components/schemas/Organisation'
              type: array
            - type: "null"
          title: Creator
          default: []
      type: object
      required:
        - id
        - publisher
        - title
        - description
        - created
        - type
        - contactPoint
      title: DataAsset
    DataAssetSummary:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        publisher:
          $ref: '#/components/schemas/Organisation'
        title:
          type: string
          title: Title
        description:
          type: string
          title: Description
        created:
          type: string
          format: date-time
          title: Created
        type:
          $ref: '#/components/schemas/assetType'
        modified:
          anyOf:
            - type: string
              format: date-time
            - type: "null"
          title: Modified
      type: object
      required:
        - id
        - publisher
        - title
        - description
        - created
        - type
      title: DataAssetSummary
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Organisation:
      properties:
        title:
          type: string
          title: Title
        id:
          type: string
          title: Id
        acronym:
          type: string
          title: Acronym
        homepage:
          type: string
          minLength: 1
          format: uri
          title: Homepage
      type: object
      required:
        - title
        - id
        - acronym
        - homepage
      title: Organisation
    SearchAssetsResponse:
      properties:
        data:
          items:
            $ref: '#/components/schemas/DataAssetSummary'
          type: array
          title: Data
        facets:
          $ref: '#/components/schemas/SearchFacets'
      type: object
      required:
        - data
        - facets
      title: SearchAssetsResponse
    SearchFacet:
      properties:
        title:
          type: string
          title: Title
        id:
          type: string
          title: Id
      type: object
      required:
        - title
        - id
      title: SearchFacet
    SearchFacets:
      properties:
        topics:
          items:
            $ref: '#/components/schemas/SearchFacet'
          type: array
          title: Topics
        organisations:
          items:
            $ref: '#/components/schemas/SearchFacet'
          type: array
          title: Organisations
        assetTypes:
          items:
            $ref: '#/components/schemas/SearchFacet'
          type: array
          title: Assettypes
      type: object
      required:
        - topics
        - organisations
        - assetTypes
      title: SearchFacets
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
    assetType:
      type: string
      enum:
        - dataService
        - dataset
      title: assetType
    organisationID:
      type: string
      enum:
        - department-for-work-pensions
        - food-standards-agency
        - nhs-digital
        - ordnance-survey
      title: organisationID
    rightsStatement:
      type: string
      enum:
        - INTERNAL
        - OPEN
        - COMMERCIAL
      title: rightsStatement
    securityClass:
      type: string
      enum:
        - OFFICIAL
        - SECRET
        - TOP_SECRET
        - NOT_APPLICABLE
      title: securityClass
