version: "3"

# volumes:
  # fuseki_storage:

services:
  fuseki:
    container_name: cddo-fuseki
    build:
      context: fuseki
      dockerfile: Dockerfile
    # volumes:
      # - fuseki_storage:/fuseki-base/databases
    ports:
      - 3030:3030
    environment:
      - ENABLE_UPDATE=true
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPLOAD=true
      